layout: sidebar
style: light
theme: jekyll-theme-slate

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 25
  exclude:
    archived: false
    forks: false
    projects:
    - OAuthAutorizer
    - AutolayoutTest
    - ViewWithShadow
    - soniccat.github.io
    - AndroidNavExperiment
    - GAPageViewController
    - iOSFontPlaygound
    - LaunchBarGlosbe
    # - LaunchBarActions
    - Role-Playing-System-V2
    - PuzzleLayout
    - wiremock
    - personal-website

social_media:
  linkedin: alexey-glushkov-46569039
  twitter: soniccat
  stackoverflow: 191027
  # behance: your_username
  # dribbble: your_username
  facebook: alexey.glushkov
  # hackerrank: your_username
  instagram: alexey.gl
  # keybase: your_username
  # mastodon: your_username
  medium: sonicCat
  # unsplash: your_username
  vk: soniccat
  website: https://www.soniccat.ru
  youtube: sonicCat
  telegram: aglushkov

post_comments:
  service: commentbox.io


# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
